In [1]:
import numpy as np

# Исходные данные
y_true = ['C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
y_pred = ['C', 'C', 'C', 'C', 'H', 'F', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'F', 'F', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H']

classes = ['C', 'F', 'H']
confusion_matrix = np.zeros((len(classes), len(classes)), dtype=int)

# Создание матрицы ошибок
for true, pred in zip(y_true, y_pred):
    i = classes.index(true)
    j = classes.index(pred)
    confusion_matrix[i, j] += 1

# Вывод матрицы ошибок
print(confusion_matrix)

# Вывод метрик
print("                Precision   Recall      F1-score    Support")

# Расчет метрик для каждого класса
precisions = []
recalls = []
f1_scores = []
supports = []

for i, c in enumerate(classes):
    tp = confusion_matrix[i, i]
    fp = sum(confusion_matrix[:, i]) - tp
    fn = sum(confusion_matrix[i, :]) - tp

    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1_score = 2 * (precision * recall) / (precision + recall)
    support = sum(confusion_matrix[i, :])
    
    precisions.append(precision)
    recalls.append(recall)
    f1_scores.append(f1_score)
    supports.append(support)

    print(f"{c: <16}{precision: <12.3f}{recall: <12.3f}{f1_score: <12.3f}{support}")

# Расчет общих метрик
accuracy = np.trace(confusion_matrix) / np.sum(confusion_matrix)
macro_avg_precision = np.mean(precisions)
macro_avg_recall = np.mean(recalls)
macro_avg_f1 = np.mean(f1_scores)

weighted_avg_precision = np.average(precisions, weights=supports)
weighted_avg_recall = np.average(recalls, weights=supports)
weighted_avg_f1 = np.average(f1_scores, weights=supports)

print(f"{'Accuracy:': <16}{'': <12}{'': <12}{accuracy: <12.3f}{np.sum(confusion_matrix)}")
print(f"{'Macro avg:': <16}{macro_avg_precision: <12.3f}{macro_avg_recall: <12.3f}{macro_avg_f1: <12.3f}{np.sum(confusion_matrix)}")
print(f"{'Weighted avg:': <16}{weighted_avg_precision: <12.3f}{weighted_avg_recall: <12.3f}{weighted_avg_f1: <12.3f}{np.sum(confusion_matrix)}")

[[4 1 1]
 [6 2 2]
 [3 0 6]]
                Precision   Recall      F1-score    Support
C               0.308       0.667       0.421       6
F               0.667       0.200       0.308       10
H               0.667       0.667       0.667       9
Accuracy:                               0.480       25
Macro avg:      0.547       0.511       0.465       25
Weighted avg:   0.581       0.480       0.464       25
